const PDFDocument = require('pdfkit');

const generateChallanPdf = (challan, res) => {
  const doc = new PDFDocument({ margin: 40 });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `inline; filename=Challan-${challan.challanNumber}.pdf`
  );

  doc.pipe(res);

  // Header section
  doc
    .fillColor('#1a365d')
    .fontSize(22)
    .text('MINI ERP OPERATIONS', { align: 'left' })
    .fontSize(10)
    .fillColor('#718096')
    .text('Wholesale & Distribution Operations Portal')
    .moveDown(0.5);

  doc
    .strokeColor('#cbd5e0')
    .lineWidth(1)
    .moveTo(40, doc.y)
    .lineTo(570, doc.y)
    .stroke()
    .moveDown(1);

  // Document metadata grid
  const topY = doc.y;
  doc
    .fillColor('#2d3748')
    .fontSize(16)
    .text(`SALES CHALLAN: ${challan.challanNumber}`, 40, topY)
    .fontSize(10)
    .fillColor('#4a5568')
    .text(`Status: ${challan.status.toUpperCase()}`)
    .text(`Created Date: ${new Date(challan.createdAt).toLocaleDateString()}`)
    .text(`Generated By: ${challan.createdByUser?.name || 'System User'}`);

  // Customer info box
  doc
    .fillColor('#1a202c')
    .fontSize(12)
    .text('Customer Information:', 340, topY)
    .fontSize(10)
    .fillColor('#4a5568')
    .text(`Name: ${challan.customer?.name || 'N/A'}`)
    .text(`Business: ${challan.customer?.businessName || 'Individual'}`)
    .text(`Phone: ${challan.customer?.mobile || 'N/A'}`)
    .text(`Address: ${challan.customer?.address || 'N/A'}`);

  doc.moveDown(2);

  // Table header
  let tableTop = Math.max(doc.y, 180);
  doc
    .rect(40, tableTop, 530, 22)
    .fill('#edf2f7');

  doc
    .fillColor('#2d3748')
    .fontSize(10)
    .text('#', 45, tableTop + 6, { width: 25 })
    .text('Product Name', 75, tableTop + 6, { width: 180 })
    .text('SKU', 260, tableTop + 6, { width: 90 })
    .text('Unit Price', 355, tableTop + 6, { width: 70, align: 'right' })
    .text('Qty', 430, tableTop + 6, { width: 50, align: 'right' })
    .text('Total', 485, tableTop + 6, { width: 80, align: 'right' });

  let y = tableTop + 28;
  let totalAmount = 0;

  challan.items?.forEach((item, index) => {
    const lineTotal = Number(item.quantity) * Number(item.unitPriceSnapshot);
    totalAmount += lineTotal;

    doc
      .fillColor('#2d3748')
      .fontSize(9)
      .text(String(index + 1), 45, y, { width: 25 })
      .text(item.productNameSnapshot || '', 75, y, { width: 180 })
      .text(item.productSkuSnapshot || '', 260, y, { width: 90 })
      .text(`RS ${Number(item.unitPriceSnapshot).toFixed(2)}`, 355, y, { width: 70, align: 'right' })
      .text(String(item.quantity), 430, y, { width: 50, align: 'right' })
      .text(`RS ${lineTotal.toFixed(2)}`, 485, y, { width: 80, align: 'right' });

    y += 20;

    doc
      .strokeColor('#e2e8f0')
      .lineWidth(0.5)
      .moveTo(40, y - 4)
      .lineTo(570, y - 4)
      .stroke();
  });

  y += 10;

  // Summary box
  doc
    .rect(340, y, 230, 45)
    .fill('#f7fafc');

  doc
    .fillColor('#2d3748')
    .fontSize(10)
    .text(`Total Items Quantity: ${challan.totalQuantity} units`, 350, y + 8)
    .fontSize(11)
    .fillColor('#1a365d')
    .text(`Grand Total: RS ${totalAmount.toFixed(2)}`, 350, y + 24);

  // Footer note
  doc
    .fontSize(8)
    .fillColor('#a0aec0')
    .text('Note: Unit prices are frozen snapshots taken at challan creation.', 40, 720, { align: 'center' })
    .text('Authorized Receiver Signature: ______________________', 350, 680);

  doc.end();
};

module.exports = {
  generateChallanPdf
};
